name: Update Contributors
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: risadams/contributors-update@v3
        with:
          repo: selectize/selectize.js
          exclude_bots: true
